# Directory where the files are located
work_dir: "/mnt/md1200/epfl_sber/massimo/PanGFS"

# Directory where the results are to be stored
results_dir: "/mnt/md1200/epfl_sber/massimo/PanGFS_res"

# Directory where conda environments are located
env_dir: "/mnt/md1200/epfl_sber/massimo/PanGFS/envs"

# Directory with scripts for analyses
scripts_dir: "/mnt/md1200/epfl_sber/massimo/PanGFS/workflow/scripts"

# Directory with the bins of interest
mags_dir: "/mnt/md1200/epfl_sber/massimo/rs_ms_bins"

# Directors of the gtdbtk database
gtdbtk_db_dir: "/mnt/esb-storage-01/NOMIS/databases/release202"

gtdbtk:
  path: "/mnt/esb-storage-01/NOMIS/databases/release202"
  threads: 48

##############################
# Taxonomies and associated info for gtotree
gtotree:
  out_list: ['GCF_001955735.1','GCF_000243275.1','GCF_001953305.1','GCF_900097105.1']
  hmm_list: ['Bacteria','Bacteria','Bacteria','Bacteria'] 
  genus_list: ['Polaromonas','Flavobacterium','Ferruginibacter','UBA1315']
